### ISSUE TITLE
http_server crash when using url without hostname

### ISSUE THREAD

**Issue by jonthn** [nanomsg/nng#821]
## NNG & Platform details.

NNG tree up to commit ebefc71efae64b72ce75efe10c447344edf7242f
Platform : macOS

## Expected Behavior

No crash

## Actual Behavior

Crash (SIGSEGV) due to NULL pointer access

## Steps to Reproduce

I'm trying to understand what is possible to do with NNG and maybe I'm using the library in the wrong way, if that's the case please tell me what I should do.
To give you some context, I'm trying to build a program that will register `rep` part with multiple URLs, so this program can respond to : 
  - /foobar1
  - /foobar/questionA
  - /foobar/something/unrelated
and I would like that each URL is handled by one thread (`pthread`) only.
To do so I was thinking to re-use the same socket (but it also crashes with multiple sockets)

Approximate code
```C
{
       // Remove all error code checking for clarity
       nng_socket sock = NNG_SOCKET_INITIALIZER;
       nng_listener listenerA = NNG_LISTENER_INITIALIZER;
       nng_listener listenerB = NNG_LISTENER_INITIALIZER;
       nng_rep0_open(&sock);
       nng_listen(sock, "ws://*:12345/foobar",  &listenerA, 0);
       nng_listen(sock, "ws://*:12345/foobar///my", &listenerB, 0);
}
```

I traced the code and found the error but I don't know what is the right fix.
The error happens in `http_server.c` https://github.com/nanomsg/nng/blob/5cbe84e69ec1567e81d919fc061377d51cd84325/src/supplemental/http/http_server.c#L931
on that line `s->hostname` is expected to be valid but in this case it is `NULL`

It comes from the fact a little bit above in function `http_server_init()` https://github.com/nanomsg/nng/blob/5cbe84e69ec1567e81d919fc061377d51cd84325/src/supplemental/http/http_server.c#L881
Here if `u_hostname` is empty (as it's my case) then `hostname` will still be `NULL`

One potential fix is like below, but I will let you be the judge.

```diff
@@ -878,11 +891,13 @@ http_server_init(nni_http_server **serverp, const nni_url *url)
                http_server_fini(s);
                return (NNG_ENOMEM);
        }
-       if ((strlen(url->u_hostname)) &&
+       if (url->u_hostname &&
```

**Comment by gdamore** [comment]
Yep, that's clearly a bug.

**Comment by gdamore** [comment]
I'm pretty sure this isn't the right fix.  The u_hostname field is supposed to always be set, even for an empty string.  So we need to fix whatever is causing this to be an empty string... probably some code in websocket somewhere.

**Comment by gdamore** [comment]
This looks weird.  The URL parser will permit a NULL value here, but only if the scheme is ipc or inproc.

The "*" field should be translated to an empty string.


I guess I could see something weird if you got into this code with a hand-crafted nng_url structure?

**Comment by gdamore** [comment]
I just added a test for this in the URL framework (not pushed yet):

```
	Convey("ws://*:12345/foobar", {
		So(nng_url_parse(&url, "ws://*:12345/foobar") == 0);
		So(url != NULL);
		So(strcmp(url->u_scheme, "ws") == 0);
		So(strcmp(url->u_host, ":12345") == 0);
		So(strcmp(url->u_hostname, "") == 0);
		So(strcmp(url->u_path, "/foobar") == 0);
		So(strcmp(url->u_port, "12345") == 0);
		So(url->u_query == NULL);
		So(url->u_fragment == NULL);
		So(url->u_userinfo == NULL);
		nng_url_free(url);
	});
```

It seems to be fine.

**Comment by gdamore** [comment]
I've also verified that the websocket listen code works with this test:

```
	Convey("Wild card hostname works", {
		nng_socket s1;
		nng_socket s2;
		char       addr[NNG_MAXADDRLEN];

		So(nng_pair_open(&s1) == 0);
		So(nng_pair_open(&s2) == 0);
		Reset({
			nng_close(s2);
			nng_close(s1);
		});
		trantest_next_address(addr, "ws://*:%u/test");
		So(nng_listen(s1, addr, NULL, 0) == 0);
		nng_msleep(100);
		// reset port back one
		trantest_prev_address(addr, "ws://127.0.0.1:%u/test");
		So(nng_dial(s2, addr, NULL, 0) == 0);
	});

```

**Comment by jonthn** [comment]
Thank you for the quick feedback, and details.
But I'm currently running all my code with `Address sanitizer` enabled in both nng and my personal code and still the same problem.
The backtrace from ASan : 

```
    #0 0x1072ca924 in wrap_strcmp (........./lib/darwin/libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x17924)
    #1 0x106fa74d6 in nni_http_server_init (........../libnng.1.1.dylib:x86_64+0xcf4d6)
    #2 0x106fc2136 in nni_ws_listener_init (........../libnng.1.1.dylib:x86_64+0xea136)
    #3 0x106f8fc17 in ws_listener_init (........../libnng.1.1.dylib:x86_64+0xb7c17)
    #4 0x106efbf37 in nni_listener_create (........./libnng.1.1.dylib:x86_64+0x23f37)
    #5 0x106edefc1 in nng_listen (........../libnng.1.1.dylib:x86_64+0x6fc1)
    ...... 
```

I updated to latest commit : ee16d11a59120cd4d981e0dcb90741fa4141372a
And I ran the tests : 

```
99% tests passed, 1 tests failed out of 69

Total Test time (real) = 220.11 sec

The following tests FAILED:
	  5 - httpclient (Child aborted)
Errors while running CTest
make: *** [test] Error 8
```

I still don't know where the problem is, but did you try with 2 listen() calls with a wildcard url ?

**Comment by jonthn** [comment]
I tried to re-create a test unit that would reproduce the problem and I was able to produce one.

```c

        Convey("Wild card hostname with port 5 digits and url", {
                nng_socket s1;
                nng_socket s2;
                char       addr[NNG_MAXADDRLEN];
                char       addr2[NNG_MAXADDRLEN];

                So(nng_pair_open(&s1) == 0);
                So(nng_pair_open(&s2) == 0);
                Reset({
                        nng_close(s2);
                        nng_close(s1);
                });
                trantest_next_address(addr, "ws://*:11223/xxxxxxx/yyyy");
                trantest_next_address(addr2, "ws://*:11223/xxxxxxx/yyyyzzz");
                warnx("\nAddr1 : %s\nAddr2 : %s", addr, addr2);
                So(nng_listen(s1, addr, NULL, 0) == 0);
                So(nng_listen(s1, addr2, NULL, 0) == 0);
                nng_msleep(100);
                // reset port back one
                trantest_prev_address(addr, "ws://127.0.0.1:11223/xxxxxxx/yyyy");
                So(nng_dial(s2, addr, NULL, 0) == 0);
        });

```

I also made it more dynamic but it's a bit 'ugly' (copy-paste of code and so on)

Full diff
```diff
diff --git a/tests/trantest.h b/tests/trantest.h
index 97fd3159..d83cc0be 100644
--- a/tests/trantest.h
+++ b/tests/trantest.h
@@ -42,11 +42,14 @@ struct trantest {
 };
 
 unsigned trantest_port = 0;
+unsigned trantest_port5 = 0;
 
 extern int  notransport(void);
 extern void trantest_checktran(const char *url);
 extern void trantest_next_address(char *out, const char *template);
+extern void trantest_next_address_5digits(char *out, const char *template);
 extern void trantest_prev_address(char *out, const char *template);
+extern void trantest_prev_address_5digits(char *out, const char *template);
 extern void trantest_init(trantest *tt, const char *addr);
 extern int  trantest_dial(trantest *tt, nng_dialer *dp);
 extern int  trantest_listen(trantest *tt, nng_listener *lp);
@@ -136,6 +139,27 @@ trantest_next_address(char *out, const char *template)
 	trantest_port++;
 }
 
+void
+trantest_next_address_5digits(char *out, const char *template)
+{
+	trantest_checktran(template);
+
+	if (trantest_port5 == 0) {
+		char *pstr;
+
+		// start at a different port each time -- 5000 - 10000 --
+		// unless a specific port is given.
+		trantest_port5 = nng_clock() % 5000 + 10000;
+		if (((pstr = ConveyGetEnv("TEST_PORT5")) != NULL) &&
+		    (atoi(pstr) != 0)) {
+			trantest_port5 = atoi(pstr);
+		}
+	}
+	(void) snprintf(out, NNG_MAXADDRLEN, template, trantest_port5);
+	trantest_port5++;
+}
+
+
 void
 trantest_prev_address(char *out, const char *template)
 {
@@ -143,6 +167,13 @@ trantest_prev_address(char *out, const char *template)
 	trantest_next_address(out, template);
 }
 
+void
+trantest_prev_address_5digits(char *out, const char *template)
+{
+	trantest_port5--;
+	trantest_next_address_5digits(out, template);
+}
+
 void
 trantest_init(trantest *tt, const char *addr)
 {
diff --git a/tests/ws.c b/tests/ws.c
index e126cb39..97ad4469 100644
--- a/tests/ws.c
+++ b/tests/ws.c
@@ -122,6 +122,29 @@ TestMain("WebSocket Transport", {
 		So(nng_dial(s2, addr, NULL, 0) == 0);
 	});
 
+	Convey("Wild card hostname with port 5 digits and url", {
+		nng_socket s1;
+		nng_socket s2;
+		char       addr[NNG_MAXADDRLEN];
+		char       addr2[NNG_MAXADDRLEN];
+
+		So(nng_pair_open(&s1) == 0);
+		So(nng_pair_open(&s2) == 0);
+		Reset({
+			nng_close(s2);
+			nng_close(s1);
+		});
+		trantest_next_address_5digits(addr, "ws://*:%u/xxxxxxx/yyyy");
+		trantest_prev_address_5digits(addr2, "ws://*:%u/xxxxxxx/yyyyzzz");
+		warnx("\nAddr1 : %s\nAddr2 : %s", addr, addr2);
+		So(nng_listen(s1, addr, NULL, 0) == 0);
+		So(nng_listen(s1, addr2, NULL, 0) == 0);
+		nng_msleep(100);
+		// reset port back one
+		trantest_prev_address_5digits(addr, "ws://127.0.0.1:%u/xxxxxxx/yyyy");
+		So(nng_dial(s2, addr, NULL, 0) == 0);
+	});
+
 	Convey("Incorrect URL paths do not work", {
 		nng_socket s1;
 		nng_socket s2;
```

Can you reproduce the crash on your side ?
I get this : 

```
  Wild card hostname works ✔✔✔✔
  Wild card hostname with port 5 digits and url ✔✔ws: 
Addr1 : ws://*:13705/xxxxxxx/yyyy
Addr2 : ws://*:13705/xxxxxxx/yyyyzzz
✔AddressSanitizer:DEADLYSIGNAL
=================================================================
==17288==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000104985925 bp 0x7ffeeb4d0c10 sp 0x7ffeeb4d0390 T0)
==17288==The signal is caused by a READ memory access.
==17288==Hint: address points to the zero page.
    #0 0x104985924 in wrap_strcmp (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x17924)
    #1 0x10482b4d6 in nni_http_server_init http_server.c:931
    #2 0x104846136 in nni_ws_listener_init websocket.c:1640
    #3 0x104813c17 in ws_listener_init websocket.c:923
    #4 0x10477ff37 in nni_listener_create listener.c:164
    #5 0x104762fc1 in nng_listen nng.c:458
    #6 0x104738515 in conveyMainImpl ws.c:84
    #7 0x10473ff12 in conveyMain convey.c:1045
    #8 0x10473a701 in main ws.c:84
    #9 0x7fff7cb3ded8 in start (libdyld.dylib:x86_64+0x16ed8)

==17288==Register values:
rax = 0x00000001056174c8  rbx = 0x0000000000000000  rcx = 0x0000614000011178  rdx = 0x00001c280000222f  
rdi = 0x000060200000fa30  rsi = 0x0000000000000000  rbp = 0x00007ffeeb4d0c10  rsp = 0x00007ffeeb4d0390  
 r8 = 0x000000000003eb2e   r9 = 0x00000001048e8878  r10 = 0x00000001048e8880  r11 = 0x0000601efb765630  
r12 = 0x0000000000000000  r13 = 0x00007ffeeb4d1720  r14 = 0x0000000000000000  r15 = 0x000060200000fa30  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x17924) in wrap_strcmp
==17288==ABORTING
```

**Comment by gdamore** [comment]
Well, you're misusing the test framework for port allocation, but it would also appear you have successfully triggered a bug in my code.  I'll look at this, because it isn't obvious at first blush how this can happen.

**Comment by gdamore** [comment]
Looking at this now, there is a clear bug.  If the server is a wildcard bind, then we don't set a hostname on the server structure, and that leads to this NULL point dereference.  Stay tuned for a fix.

**Comment by gdamore** [comment]
There is a similar problem with a null port.
